# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Yourder' do

end

target 'YourderTests' do

end

target 'YourderUITests' do

end

pod 'Google/SignIn'

pod ‘Braintree’

